title: "Joel's Blog"
description: "Stories, coding, and the creative spark"
baseurl: "/blog"           # This is crucial for GitHub Pages under /blog
url: "https://thejupiterdev.github.io"  # Your GitHub Pages root URL

# Optional but helpful
author: Joel H.
timezone: America/New_York
markdown: kramdown
theme: minima              # Required by GitHub Pages even if you're not using it

# Avoid processing these files/folders
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

# Enable excerpts for post previews
excerpt_separator: "<!--more-->"
