title: Joel’s Blog
description: "Updates, thoughts, and coffee-fueled ideas."
baseurl: "" # it's already at /blog
url: "https://thejupiterdev.github.io"

markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
